version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: {NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: {CLERK_SECRET_KEY}
      ENCRYPTION_SECRET_KEY: {ENCRYPTION_SECRET_KEY}
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
